"""add public_id to models

Revision ID: 782d9c723b3d
Revises: 826366372571
Create Date: 2026-03-04 19:51:32.816674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782d9c723b3d'
down_revision = '826366372571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('ssl_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('ssl_certificates', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('notification_rules', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
